title: Hassan El Hajj
logo: ./assets/profile.jpg
description: Senior IT & Cybersecurity Expert • Transitioning to Research • Non-profit Founder • Security & Privacy Enthusiast
theme: jekyll-theme-minimal
